export const firestoreCollections = {
  users: {
    uid: "string",
    role: "farmer | buyer | admin | investor | partner",
    name: "string",
    email: "string",
    phone: "string",
    photoURL: "string",
    status: "active | pending | suspended",
    createdAt: "timestamp",
    updatedAt: "timestamp",
  },
  farmers: {
    userId: "users/{uid}",
    farmName: "string",
    location: "geopoint",
    state: "string",
    country: "string",
    verificationStatus: "pending | verified | rejected",
    livestockCount: "number",
    revenueToDate: "number",
  },
  buyers: {
    userId: "users/{uid}",
    organizationName: "string",
    procurementType: "retail | processor | exporter | government | enterprise",
    preferredLocations: "string[]",
    verificationStatus: "pending | verified | rejected",
  },
  livestock: {
    animalId: "string",
    farmerId: "farmers/{id}",
    species: "goat | cattle | sheep | poultry | pig | other",
    breed: "string",
    dateOfBirth: "timestamp",
    qrCodeUrl: "string",
    healthScore: "number",
    verificationStatus: "pending | verified | rejected",
    currentOwnerId: "users/{uid}",
    farmLocation: "geopoint",
    weightRecords: "array<{weight:number, recordedAt:timestamp}>",
    ownershipHistory: "array<{ownerId:string, from:timestamp, to?:timestamp}>",
  },
  vaccinations: {
    livestockId: "livestock/{id}",
    vaccineName: "string",
    administeredBy: "string",
    administeredAt: "timestamp",
    nextDueAt: "timestamp",
    proofUrl: "string",
  },
  medical_records: {
    livestockId: "livestock/{id}",
    symptoms: "string[]",
    diagnosis: "string",
    treatment: "string",
    veterinarianId: "users/{uid}",
    createdAt: "timestamp",
  },
  marketplace_listings: {
    livestockId: "livestock/{id}",
    sellerId: "users/{uid}",
    price: "number",
    currency: "NGN",
    status: "draft | active | reserved | sold | removed",
    location: "geopoint",
    minimumOrderQuantity: "number",
  },
  orders: {
    buyerId: "users/{uid}",
    sellerId: "users/{uid}",
    listingIds: "string[]",
    status: "requested | accepted | paid | in_transit | delivered | disputed",
    amount: "number",
    paymentReference: "string",
  },
  deliveries: {
    orderId: "orders/{id}",
    logisticsPartnerId: "partners/{id}",
    pickupLocation: "geopoint",
    dropoffLocation: "geopoint",
    status: "scheduled | picked_up | in_transit | delivered",
  },
  reviews: {
    orderId: "orders/{id}",
    reviewerId: "users/{uid}",
    rating: "number",
    comment: "string",
  },
  messages: {
    threadId: "string",
    senderId: "users/{uid}",
    recipientId: "users/{uid}",
    body: "string",
    createdAt: "timestamp",
  },
  notifications: {
    userId: "users/{uid}",
    type: "system | marketplace | health | payment | verification",
    title: "string",
    body: "string",
    read: "boolean",
  },
  investor_leads: {
    name: "string",
    email: "string",
    organization: "string",
    ticketSize: "string",
    status: "new | contacted | data_room | committed | closed",
  },
  partners: {
    name: "string",
    category: "veterinary | logistics | buyer | development | government | finance",
    contactEmail: "string",
    status: "prospect | active | inactive",
  },
  waitlist: {
    name: "string",
    email: "string",
    segment: "farmer | buyer | investor | partner",
    country: "string",
    createdAt: "timestamp",
  },
} as const;
